# Generated by Django 2.1.3 on 2018-11-07 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('msg_from', models.BinaryField(default=1)),
                ('msg_to', models.BinaryField(default=0)),
                ('msg_time', models.TimeField(auto_now=True)),
                ('msg_text', models.TextField(max_length=2000)),
            ],
        ),
    ]
