# Generated by Django 2.1.3 on 2018-11-07 18:32

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0003_auto_20181107_1830'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_from',
            field=models.IntegerField(default=1),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_time',
            field=models.TimeField(default=datetime.datetime(2018, 11, 7, 18, 32, 44, 117654)),
        ),
        migrations.AlterField(
            model_name='message',
            name='msg_to',
            field=models.IntegerField(default=0),
        ),
    ]
