# Generated by Django 2.1.3 on 2018-11-12 11:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0006_auto_20181107_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='message',
            name='msg_time',
            field=models.TimeField(default=datetime.datetime(2018, 11, 12, 16, 53, 54, 130309)),
        ),
    ]
