# Generated by Django 2.1.3 on 2018-11-21 11:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chat', '0007_auto_20181112_1653'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Message',
        ),
    ]
